version: "3.7"
#https://github.com/mvillarrealb/docker-spark-cluster/blob/master/articles/docker-compose.md
#https://www.youtube.com/watch?v=l6Ta75ZSXi4

networks:
  zookeeper-network:
    driver: bridge

services:
  ######################  zookeeper-1 ##########################
  zookeeper-1:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    container_name: $zookeeper_worker_1
    working_dir: $zookeeper_home
    ports:
      - 2181:2181 #client connections
      - 2788:2788 #follower connections
      - 3788:3788 #leader election
    volumes:
      - ./conf:$zookeeper_home/conf
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "$zookeeper_home/conf/zookeeper_init.sh &&
          $zookeeper_home/bin/zkServer.sh start-foreground"
      ]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=1
    networks:
      - zookeeper-network
  ######################  zookeeper-2 ##########################
  zookeeper-2:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    container_name: $zookeeper_worker_2
    working_dir: $zookeeper_home
    ports:
      - 2281:2181 #client connections
      - 2888:2788 #follower connections
      - 3888:3788 #leader election
    volumes:
      - ./conf:$zookeeper_home/conf
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "$zookeeper_home/conf/zookeeper_init.sh &&
          $zookeeper_home/bin/zkServer.sh start-foreground"
      ]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=2
    networks:
      - zookeeper-network
  ######################  zookeeper-3 ##########################
  zookeeper-3:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    container_name: $zookeeper_worker_3
    working_dir: $zookeeper_home
    ports:
      - 2381:2181 #client connections
      - 2988:2788 #follower connections
      - 3988:3788 #leader election
    volumes:
      - ./conf:$zookeeper_home/conf
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "$zookeeper_home/conf/zookeeper_init.sh &&
          $zookeeper_home/bin/zkServer.sh start-foreground"
      ]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=3
    networks:
      - zookeeper-network
  ######################  kafka-broker-1 ##########################
  kafka-broker-1:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: $kafka_broker_1
    working_dir: $kafka_home
    volumes:
      - ./conf:$kafka_home/custom
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2281,zookeeper-3:2381
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-1:9092
    entrypoint:
      #https://stackoverflow.com/questions/39759071/error-while-starting-kafka-broker 
      #Add 20 second delay to avoid this problem that occurs when you start kafka before zookeeper nodes joined each other
      [
        "/bin/bash",
        "-c",
        "sleep 20 && $kafka_home/custom/kafka_init.sh &&
          $kafka_home/bin/kafka-server-start.sh
          $kafka_home/config/server.properties"
      ]
    networks:
      - zookeeper-network
  ######################  kafka-broker-2 ##########################      
  kafka-broker-2:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: $kafka_broker_2
    working_dir: $kafka_home
    ports:
      - 9192:9092
    volumes:
      - ./conf:$kafka_home/custom
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2281,zookeeper-3:2381
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9092
    entrypoint:
      #https://stackoverflow.com/questions/39759071/error-while-starting-kafka-broker 
      #Add 20 second delay to avoid this problem that occurs when you start kafka before zookeeper nodes joined each other
      [
        "/bin/bash",
        "-c",
        "sleep 20 && $kafka_home/custom/kafka_init.sh &&
          $kafka_home/bin/kafka-server-start.sh
          $kafka_home/config/server.properties"
      ]
    networks:
      - zookeeper-network
  ######################  kafka-broker-3 ##########################      
  kafka-broker-3:
    build:
      context: .
      dockerfile: $docker_file_name
    image: cluster-apache-zookeeper:$zookeeper_version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: $kafka_broker_3
    working_dir: $kafka_home
    ports:
      - 9292:9092
    volumes:
      - ./conf:$kafka_home/custom
      - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2281,zookeeper-3:2381
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-3:9092
    entrypoint:
      #https://stackoverflow.com/questions/39759071/error-while-starting-kafka-broker 
      #Add 20 second delay to avoid this problem that occurs when you start kafka before zookeeper nodes joined each other
      [
        "/bin/bash",
        "-c",
        "sleep 20 && $kafka_home/custom/kafka_init.sh &&
          $kafka_home/bin/kafka-server-start.sh
          $kafka_home/config/server.properties"
      ]
    networks:
      - zookeeper-network
